version: "3.4"

services:
  redis:
    image: redis:7.2.3-alpine
    command: redis-server --lazyfree-lazy-user-del yes
    ports:
      - "6379:6379"

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6380:6379"
    ulimits:
      memlock: -1
