services:
  redis:
    image: redis:7.4.1-alpine
    ports:
      - "6379:6379"

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6380:6379"

  valkey:
    image: valkey/valkey:8.0.2-alpine
    ports:
      - "6381:6379"