services:
  redis:
    image: redis:7.4.0-alpine
    ports:
      - "6379:6379"

  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    ports:
      - "6380:6379"

  valkey:
    image: valkey/valkey:7.2.6-alpine
    ports:
      - "6381:6379"